// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShop.CouponService.EntityFrameworkCore;

#nullable disable

namespace eShop.CouponService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(CouponServiceDbContext))]
    partial class CouponServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShop.CouponService.Domain.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("MinAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78dc2c06-15c5-4e15-bbd8-5f352d397ea9"),
                            CouponCode = "10OFF",
                            DiscountAmount = 10m,
                            MinAmount = 10
                        },
                        new
                        {
                            Id = new Guid("792bedc4-6eb8-4366-a4c7-b7589ad3980e"),
                            CouponCode = "20OFF",
                            DiscountAmount = 20m,
                            MinAmount = 40
                        },
                        new
                        {
                            Id = new Guid("0413f510-2336-4f22-b2fb-059eafc7f559"),
                            CouponCode = "30OFF",
                            DiscountAmount = 30m,
                            MinAmount = 600
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
