// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShop.ProductService.EntityFrameworkCore;

#nullable disable

namespace eShop.ProductService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ProductServiceDbContext))]
    partial class ProductServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShop.ProductService.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54b68877-92f4-45a0-8f4b-7bb969843a92"),
                            CategoryName = "Appetizer",
                            Description = "Each cabin has a large sail, so that the vehicles do not have room for visitors.<br/> Gas box coupons, biggest vikings. Upgrade your courses at a comfortable price.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Samosa",
                            Price = 150.0
                        },
                        new
                        {
                            Id = new Guid("c997f0a0-07d1-4c2a-b9ac-08aa6ccda2e0"),
                            CategoryName = "Appetizer",
                            Description = "Smoking or leakage and large, shooting vehicles may not be leakage.<br/> Spotlight scores, not the biggest vikings. Please upgrade the course cost.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Paneer Tikka",
                            Price = 200.0
                        },
                        new
                        {
                            Id = new Guid("bfb587bd-d807-44dc-9867-e7179c6b8e1f"),
                            CategoryName = "Dessert",
                            Description = "Smoking or leakage and large, shooting vehicles may not be leakage.<br/> Spotlight scores, not the biggest vikings. Please upgrade the course cost.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Sweet Pie",
                            Price = 250.0
                        },
                        new
                        {
                            Id = new Guid("815f1b71-7d4d-4816-8bdd-d40f81757ffc"),
                            CategoryName = "Entree",
                            Description = " Smoking or leakage and large, shooting vehicles may not be leakage.<br/> Spotlight scores, not the biggest vikings. Please upgrade the course cost.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Pav Bhaji",
                            Price = 2500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
